name: PHPUnit

on: [ push, pull_request ]

env:
  SWOOLE_VERSION: '5.1.1'
  SWOW_VERSION: 'v1.2.0'

jobs:
  ci:
    name: Test PHP ${{ matrix.php-version }} on Elastic ${{ matrix.elasticsearch }}
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php-version: [ '8.1', '8.2', '8.3' ]
        elasticsearch: [ '7.17.22', '8.14.1' ]
      max-parallel: 9
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: phpize
          ini-values: opcache.enable_cli=0
          coverage: none
      - name: Setup Services
        run: |
          docker run -d -p 9200:9200 -p 9300:9300 -e "discovery.type=single-node" --name elasticsearch elasticsearch:${{ matrix.elasticsearch }}
          sleep 5
          php tests/put_documents.php
      - name: Setup Packages
        run: composer update -o --no-scripts
      - name: Run Test Cases
        run: |
          vendor/bin/php-cs-fixer fix --dry-run
          composer analyse
          composer test
